root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - 'vue'
  - '@typescript-eslint'
rules:
  vue/html-self-closing: 'off'
  vue/html-indent: 'off'
  vue/html-closing-bracket-newline: 'off'
  vue/singleline-html-element-content-newline: 'off'
